### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by oodler577** [retrodores/XVI#1]
FOR 1.0
- [x] figure out true vi bindings (`esc` when in _insert_ mode to get to _nav_, `esc+i` to insert, `esc+:` for command)
- [x] figure out file buffering for 2d navigation `j`,`k`,`h`,`l`
- [x] figure out load
- [ ] prevent program from crashing when loaded text is wider than emulator viewport
- [x] figure out save
- [ ] figure out transparent cursor to see character beneath
